### ISSUE TITLE
Unwrapped java.net.SocketTimeoutException when streaming 2xx responses

### ISSUE THREAD

**Issue by wchau** [com-lihaoyi/requests-scala#102]
Exception in thread "main" java.net.SocketTimeoutException: Read timed out 
  at java.base/java.net.SocketInputStream.socketRead0(Native Method)
  at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
  at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
  at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
  at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
  at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
  at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
  at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1374)
  at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:985)
  at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
  at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
  at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
  at java.base/sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:245)
  at java.base/sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:692)
  at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
  at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510)
  at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:243)
  at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
  at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
  at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
  at geny.Internal$.transfer0(Internal.scala:40)
  at geny.Internal$.transfer(Internal.scala:61)
  at geny.Readable.$anonfun$writeBytesTo$2(Writable.scala:93)
  at geny.Readable.$anonfun$writeBytesTo$2$adapted(Writable.scala:93)
  at requests.Requester$$anon$1.processWrappedStream$1(Requester.scala:341)
  at requests.Requester$$anon$1.readBytesThrough(Requester.scala:348)
  at geny.Readable.writeBytesTo(Writable.scala:93)
  at geny.Readable.writeBytesTo$(Writable.scala:93)
  at requests.Requester$$anon$1.writeBytesTo(Requester.scala:165)
  at requests.Requester.apply(Requester.scala:114)

**Comment by lihaoyi** [comment]
Going to call this moot since https://github.com/com-lihaoyi/requests-scala/pull/158 has overhauled the exception handling logic. If any exception-related issues still remain in 0.9.0, please open new issues
