### ISSUE TITLE
request's encoding is corrupt

### ISSUE THREAD

**Issue by yairogen** [com-lihaoyi/requests-scala#88]
When trying to setup gzip request, I get from server a 400 response:
```
The request content was malformed:
The request's encoding is corrupt
	at requests.Requester$$anon$1.readBytesThrough(Requester.scala:356)
	at geny.Readable.writeBytesTo(Writable.scala:93)
	at geny.Readable.writeBytesTo$(Writable.scala:93)
	at requests.Requester$$anon$1.writeBytesTo(Requester.scala:165)
	at requests.Requester.apply(Requester.scala:114)
```

Please see attached simple main that shows the issue.

Note: apache client works find against  server, hence I think it's an issue in requests impl
[HttpServerRoutingMinimal.zip](https://github.com/com-lihaoyi/requests-scala/files/6733635/HttpServerRoutingMinimal.zip)

**Comment by yairogen** [comment]
@lihaoyi  is this known issue?

**Comment by lihaoyi** [comment]
@yairogen any chance you could provide a build file to go along with the source code? Otherwise I'm not sure how to reproduce
